import { generateMetadata } from '../components/MetaData';
import AboutClient from './AboutClient';

export const metadata = generateMetadata({
  title: 'Create Next App | About',
  description: 'Generated by create next app | About',
  image: 'globe.svg',
});

export default function About() {
  return <AboutClient />;
}
