import type { Metadata } from 'next';
import AboutClient from './AboutClient';

export const metadata: Metadata = {
  title: 'Create Next App | About',
  description: 'Generated by create next app | About',
};

export default function About() {
  return <AboutClient />;
}
