import type { Metadata } from 'next';
import ContactClient from './ContactClient';

export const metadata: Metadata = {
  title: 'Create Next App | Contact',
  description: 'Generated by create next app | Contact',
};

export default function Contact() {
  return <ContactClient />;
}
