import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';
import { DevLinkProvider } from '@/devlink/DevLinkProvider';
import Navbar from './components/Navbar';
import Footer from './components/Footer';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <main>
          <DevLinkProvider>
            <Navbar />
            {children}
            <Footer />
          </DevLinkProvider>
        </main>
      </body>
    </html>
  );
}
